
const TermsAndConditions = () => {
  return (
    <div className="terms-container">
      <h1 className="terms-head">Terms & Conditions</h1>

      <p>
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules there under as applicable and the
        amended provisions pertaining to electronic records in various statutes
        as amended by the Information Technology Act, 2000. This electronic
        record is generated by a computer system and does not require any
        physical or digital signatures.
      </p>

      <p>
        This document is published in accordance with Rule 3 (1) of the
        Information Technology (Intermediaries Guidelines) Rules, 2011 that
        require publishing the rules and regulations, privacy policy and Terms
        of Use for access or usage of domain name
        https://zenvytechnolohies.vercel.app/ ("Website"), including the related
        mobile site and mobile application (hereinafter referred to as
        "Platform").
      </p>

      <p>
        The Platform is owned by Zenvy Technologies, with its registered office
        at Tiruvannamalai (hereinafter referred to as “Platform Owner”, "we",
        "us", "our").
      </p>

      <h2>Acceptance of Terms</h2>
      <p>
        ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
        AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.
      </p>

      <h2>User Responsibilities</h2>
      <p>
        To access and use the Services, you agree to provide true, accurate and
        complete information during and after registration. You are responsible
        for all activities under your account.
      </p>

      <h2>No Warranty</h2>
      <p>
        Neither we nor any third parties provide any warranty or guarantee as
        to the accuracy, timeliness, performance, completeness or suitability
        of the information and materials offered on this website.
      </p>

      <h2>Intellectual Property</h2>
      <p>
        The contents of the Platform including design, layout, look, graphics
        and content are proprietary to us. Unauthorized use may result in legal
        action.
      </p>

      <h2>Payments</h2>
      <p>
        You agree to pay the charges associated with availing the Services.
        Upon initiating a transaction, you enter into a legally binding
        contract with the Platform Owner.
      </p>

      <h2>Prohibited Use</h2>
      <p>
        You agree not to use the Platform for any unlawful, illegal or
        prohibited purpose under Indian laws.
      </p>

      <h2>Third Party Links</h2>
      <p>
        The Platform may contain links to third-party websites. We are not
        responsible for their content or policies.
      </p>

      <h2>Indemnification</h2>
      <p>
        You shall indemnify and hold harmless the Platform Owner and its
        affiliates from any claims arising from your breach of these Terms.
      </p>

      <h2>Force Majeure</h2>
      <p>
        The parties shall not be liable for failure to perform obligations due
        to events beyond reasonable control.
      </p>

      <h2>Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the
        laws of India.
      </p>

      <h2>Jurisdiction</h2>
      <p>
        All disputes shall be subject to the exclusive jurisdiction of the
        courts in Tiruvannamalai, Tamil Nadu.
      </p>

      <h2>Contact Information</h2>
      <p>
        For any concerns regarding these Terms, please contact us through the
        contact details provided on our website.
      </p>
    </div>
  );
};
export default TermsAndConditions;
